version: '3.7'
services:

  odoo:
    image: odoo:14
    restart: always
    depends_on:
      - db
    environment:
      - LANG=pt_BR.UTF-8
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ODOO_RC=${ODOO_RC:-/etc/odoo/odoo.conf}
      - VIRTUAL_HOST=${VIRTUAL_HOST:-localhost}
      - VIRTUAL_PORT=${VIRTUAL_PORT:-80}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST:-}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-hugo.rebelo@indigoway.com}
    expose:
     - "8069"
     - "8071"
     - "8072"
    volumes:
      # Filestore
      - ./odoo-web-data:/var/lib/odoo/
      # Configration files
      - ./config/odoo:/etc/odoo
      # Addons 
      - ./addons:/mnt/extra-addons
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"


  db:
    image: postgres:10.5
    restart: always
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:9432:5432"
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  default:
    name: moveon-odoo-net
