version: '3'
services:
  odoo:
    container_name: odoo
    image: odoo:latest
    volumes:
        - ./addons-extra:/mnt/extra-addons
        - ./etc/odoo/config:/etc/odoo
        - odoo-web-data:/var/lib/odoo
    ports:
        - "8069:8069"
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./nginx/conf:/etc/nginx/conf.d
volumes:
    odoo-web-data: