version: '3'
services:
    odoo:
        container_name: odoo
        image: odoo:latest
        restart: always
        volumes:
            - ./addons:/mnt/extra-addons/:rw
            - ./config/odoo:/etc/odoo/:rw
            - ./odoo-web-data:/var/lib/odoo/:rw
        ports:
            - "8069:8069"
        depends_on:
            - "db"
        networks:
          - odoo_network
    nginx:
        container_name: nginx
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./config/nginx/conf:/etc/nginx/conf.d/:rw
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        depends_on:
            - "odoo"
        networks:
            - odoo_network
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email youremail@email.com -d domain.com.br --agree-tos
        depends_on:
            - nginx
        networks:
          - odoo_network

    db:
      image: postgres:13
      restart: always
      container_name: postgresql
      environment:
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
        - POSTGRES_DB=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - "127.0.0.1:9432:5432"
      volumes:
        - ./odoo-db-data:/var/lib/postgresql/data/pgdata
      networks:
        - odoo_network
      logging:
        driver: json-file
        options:
          max-size: "30m"
          max-file: "10"

networks:
  odoo_network:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
